name: aws-us-east-2
on:
  push:
    branches:
      - main
concurrency: off
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: aws-us-east-2
    steps:

      - uses: actions/checkout@v3.3.0

      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - shell: bash
        run: python3 -m venv .venv

      - shell: bash
        run: .venv/bin/pip install -r requirements.txt

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.12.1'

      - shell: bash
        run: npm install -g aws-cdk@2.63.0

      - shell: bash
        run: cdk deploy
